local input = require("systems.input")

function init(self)
    self.dragging = false
    input.register(msg.url("."))
    go.set_scale_xy(0.6)
end

function final(self)
    input.unregister(msg.url("."))
end

function update(self, dt)

end

function on_message(self, message_id, message, sender)
    if message_id ~= hash("input") then
        return
    end

    local action_id = message.action_id
    local action = message.action

    if action_id == hash("mouse_button_1") or action_id == hash("touch") then
        if action.pressed then
            self.dragging = true
        end

        if action.released then
            self.dragging = false
        end
    end

    if self.dragging then
        local new_pos = camera.screen_xy_to_world(action.screen_x, action.screen_y)
        new_pos.z = go.get_position().z
        go.set_position(new_pos)
    end
end
