local M = {}

local function find_roots(path, out_collections, out_guis)
    local children = editor.get(path, 'children')
    for _, child_path in ipairs(children) do
        if child_path:match('%.collection$') then
            table.insert(out_collections, child_path)
        elseif child_path:match('%.gui$') then
            table.insert(out_guis, child_path)
        elseif editor.can_get(child_path, 'children') then
            find_roots(child_path, out_collections, out_guis)
        end
    end
end

local function try_get(node_id, property)
    if editor.can_get(node_id, property) then
        return editor.get(node_id, property)
    end
end

local function basename_no_ext(path)
    return path:match("([^/]+)%.%w+$")
end

local function parse_component(parent_scope, node_id)
    local type = try_get(node_id, 'type')
    local name = try_get(node_id, 'id')
    local url = parent_scope.url .. '#' .. name

    local scope = {
        type = type,
        name = name,
        url = url,
        path = try_get(node_id, 'path'),
    }
    table.insert(parent_scope.components, scope)
end

local function parse_go(parent_scope, node_id)
    local type = try_get(node_id, 'type')
    local name = try_get(node_id, 'id')
    local url = parent_scope.url .. '/' .. name

    local scope = {
        type = type,
        name = name,
        url = url,
        game_objects = {},
        components = {},
    }
    table.insert(parent_scope.game_objects, scope)

    local components = try_get(node_id, 'components') or {}
    for _, component_id in ipairs(components) do
        parse_component(scope, component_id)
    end

    local children = try_get(node_id, 'children') or {}
    for _, child_id in ipairs(children) do
        parse_go(scope, child_id)
    end
end

local function parse_collection(parent_scope, path)
    local name = basename_no_ext(path)
    local url = name .. ':'
    local scope = { name = name, url = url, game_objects = {} }
    table.insert(parent_scope.collections, scope)

    local child_nodes = try_get(path, 'children') or {}

    for _, child_id in ipairs(child_nodes) do
        parse_go(scope, child_id)
    end
end

local function parse_gui(parent_scope, path)
    --local name = basename_no_ext(path)
    --local url = name
    --local scope = { url = url }
    --parent_scope[name] = scope
    --
    --child_nodes = try_get(path, 'nodes') or {}
    --
    --for _, child_id in ipairs(child_nodes) do
    --    parse_go(scope, child_id)
    --end
end

function M.get_commands()
    return {
        {
            label = 'Generate TS Definitions',
            locations = { 'Assets' }, -- Right-click in Assets pane
            query = {
                selection = { type = 'resource', cardinality = 'one' }
            },
            active = function(opts)
                return editor.can_get(opts.selection, 'children')
            end,
            run = function(opts)
                local collections = {}
                local guis = {}
                find_roots(opts.selection, collections, guis)

                local scope = {
                    collections = {},
                    guis = {},
                }

                for _, path in ipairs(collections) do
                    parse_collection(scope, path)
                end

                --for _, path in ipairs(guis) do
                --    parse_gui(scope.guis, path)
                --end

                pprint(scope)

                -- Write the file to the project root
                -- Note: Editor scripts use standard Lua io for file writing
                --local file = io.open('collection_types.d.ts', 'w')
                --if file then
                --    file:write(ts_content)
                --    file:close()
                --    print('TS Definitions generated successfully!')
                --else
                --    print('Error: Could not write file.')
                --end
            end
        }
    }
end

return M
    