local state_manager = require("game.state.state_manager")
local input = require("systems.input")
local const = require("game.data.const")

function init(self)
    go.set_position(vmath.vector3(const.DESIGN_WIDTH / 2, const.DESIGN_HEIGHT / 2, 0))
    msg.post(".", "acquire_input_focus")

    window.set_listener(window_callback)

    state_manager.init()
    state_manager.switch("core")
end

function update(self, dt)
	state_manager.update(dt)
end

function on_message(self, message_id, message, sender)
	state_manager.on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    input.on_input(action_id, action)
end

function window_callback(self, event, data)
    if event == window.WINDOW_EVENT_RESIZED then
        
    end
end