local state_manager = require("game.state.state_manager")
local input = require("systems.input")

function init(self)
	msg.post(".", "acquire_input_focus")

	state_manager.init()
	state_manager.switch("core")
end

function update(self, dt)
	state_manager.update(dt)
end

function on_message(self, message_id, message, sender)
	state_manager.on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	input.on_input(action_id, action)
end