export enum Easing {
	Linear = 'EASING_LINEAR',

	SinIn = 'EASING_INSINE',
	SinOut = 'EASING_OUTSINE',
	SinInOut = 'EASING_INOUTSINE',
	SinOutIn = 'EASING_OUTINSINE',

	BackIn = 'EASING_INBACK',
	BackOut = 'EASING_OUTBACK',
	BackInOut = 'EASING_INOUTBACK',
	BackOutIn = 'EASING_OUTINBACK',

	BounceIn = 'EASING_INBOUNCE',
	BounceOut = 'EASING_OUTBOUNCE',
	BounceInOut = 'EASING_INOUTBOUNCE',
	BounceOutIn = 'EASING_OUTINBOUNCE',

	ElasticIn = 'EASING_INELASTIC',
	ElasticOut = 'EASING_OUTELASTIC',
	ElasticInOut = 'EASING_INOUTELASTIC',
	ElasticOutIn = 'EASING_OUTINELASTIC',

	ExpIn = 'EASING_INEXPO',
	ExpOut = 'EASING_OUTEXPO',
	ExpInOut = 'EASING_INOUTEXPO',
	ExpOutIn = 'EASING_OUTINEXPO',

	CircularIn = 'EASING_INCIRC',
	CircularOut = 'EASING_OUTCIRC',
	CircularInOut = 'EASING_INOUTCIRC',
	CircularOutIn = 'EASING_OUTINCIRC',

	QuadIn = 'EASING_INQUAD',
	QuadOut = 'EASING_OUTQUAD',
	QuadInOut = 'EASING_INOUTQUAD',
	QuadOutIn = 'EASING_OUTINQUAD',

	CubicIn = 'EASING_INCUBIC',
	CubicOut = 'EASING_OUTCUBIC',
	CubicInOut = 'EASING_INOUTCUBIC',
	CubicOutIn = 'EASING_OUTINCUBIC',

	QuartIn = 'EASING_INQUART',
	QuartOut = 'EASING_OUTQUART',
	QuartInOut = 'EASING_INOUTQUART',
	QuartOutIn = 'EASING_OUTINQUART',

	QuintIn = 'EASING_INQUINT',
	QuintOut = 'EASING_OUTQUINT',
	QuintInOut = 'EASING_INOUTQUINT',
	QuintOutIn = 'EASING_OUTINQUINT',
}
