export enum Playback {
	PLAYBACK_ONCE_FORWARD = 'PLAYBACK_ONCE_FORWARD',
	PLAYBACK_ONCE_BACKWARD = 'PLAYBACK_ONCE_BACKWARD',
	PLAYBACK_ONCE_PINGPONG = 'PLAYBACK_ONCE_PINGPONG',
	PLAYBACK_LOOP_FORWARD = 'PLAYBACK_LOOP_FORWARD',
	PLAYBACK_LOOP_BACKWARD = 'PLAYBACK_LOOP_BACKWARD',
	PLAYBACK_LOOP_PINGPONG = 'PLAYBACK_LOOP_PINGPONG',
}
